### ISSUE TITLE
Better handling for HTML emails

### ISSUE THREAD

**Issue by victoriadrake** [victoriadrake/rss-mailer#1]
**Is your feature request related to a problem? Please describe.**

HTML markup for rich emails is currently handled with a couple cumbersome strings:

https://github.com/victoriadrake/rss-mailer/blob/249fce933760e3e44d84f7637ad91ef129b4f7c1/main.go#L209-L210

**Describe the solution you'd like**

Email styling and HTML should be easier to edit and maintain.

**Describe alternatives you've considered**

- An external filesystem can be used to house a file that the Lambda function can read from. [Here's one example](https://aws.amazon.com/blogs/aws/new-a-shared-file-system-for-your-lambda-functions/).

- Strings can be stored as environment variables, but the necessary escaping makes HTML even more cumbersome.

**Comment by bikerwhocodes** [comment]
Hey Victoria,
Just created a pull request, take a look.
Hope it helps :)

N.

**Comment by bikerwhocodes** [comment]
What happened why did u close the PR?

**Comment by victoriadrake** [comment]
My mistake, see https://github.com/victoriadrake/rss-mailer/pull/2#issuecomment-737608307
